# Generated by Django 6.0 on 2026-01-07 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientBranding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("primary_color", models.CharField(default="#0f766e", max_length=7)),
                ("secondary_color", models.CharField(default="#1e293b", max_length=7)),
                ("accent_color", models.CharField(default="#f59e0b", max_length=7)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("favicon_url", models.URLField(blank=True, null=True)),
                ("company_name", models.CharField(blank=True, max_length=100)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("website", models.URLField(blank=True, null=True)),
                ("features", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branding",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Branding",
                "verbose_name_plural": "Client Branding",
                "db_table": "client_branding",
            },
        ),
        migrations.CreateModel(
            name="DeliverablePage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                ("template", models.CharField(default="default", max_length=50)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverable_pages",
                        to="clients.client",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="deliverables.deliverablepage",
                    ),
                ),
            ],
            options={
                "db_table": "deliverable_pages",
                "ordering": ["order", "title"],
                "unique_together": {("client", "slug")},
            },
        ),
        migrations.CreateModel(
            name="DeliverableSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Section"),
                            ("features", "Features Grid"),
                            ("pricing", "Pricing Table"),
                            ("timeline", "Timeline"),
                            ("content", "Rich Content"),
                            ("table", "Data Table"),
                            ("gallery", "Image Gallery"),
                            ("cta", "Call to Action"),
                            ("custom", "Custom HTML"),
                        ],
                        default="content",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField(blank=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("order", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="deliverables.deliverablepage",
                    ),
                ),
            ],
            options={
                "db_table": "deliverable_sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ClientDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("architecture", "Architecture"),
                            ("status", "Project Status"),
                            ("changelog", "Changelog"),
                            ("design", "Design"),
                            ("ux", "UX/UI"),
                            ("api", "API Documentation"),
                            ("guide", "User Guide"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_public", models.BooleanField(default=False)),
                ("is_pinned", models.BooleanField(default=False)),
                ("version", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "client_documents",
                "ordering": ["-is_pinned", "-updated_at"],
                "unique_together": {("client", "slug")},
            },
        ),
    ]
