# Generated by Django 6.0 on 2026-01-07 10:13

import uuid
from django.db import migrations, models


def create_clients_table(apps, schema_editor):
    """Create the clients table if it doesn't exist."""
    if schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute("""
            CREATE TABLE IF NOT EXISTS "clients" (
                "id" char(32) NOT NULL PRIMARY KEY,
                "name" varchar(255) NOT NULL,
                "slug" varchar(100) NOT NULL UNIQUE,
                "created_at" datetime NOT NULL,
                "updated_at" datetime NOT NULL
            )
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_clients_table, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="client",
            options={},
        ),
    ]
